### ISSUE TITLE
Fórmulas | Área de figuras planas | Retângulo

### ISSUE THREAD

**Issue by laisfrigerio** [laisfrigerio/math-solver#3]
Desenvolver em javascript

**Comment by Diegoslourenco** [comment]
Posso te ajudar com isso?

**Comment by laisfrigerio** [comment]
opa Diegoslourenco, pode sim

Lembrando que o projeto está em engatinhando ainda e precisamos pensar na parte de compilação do javascript ao utilizar as versões mais recente (ES6. ES8, etc)

**Comment by Diegoslourenco** [comment]
@laisfrigerio como estou começando em javascript acho melhor eu aguardar ter essas definições

**Comment by laisfrigerio** [comment]
@Diegoslourenco  entre hoje e amanhã eu defino. Na sequência eu te aviso!!!

**Comment by laisfrigerio** [comment]
@Diegoslourenco Está ajustado a compilação dos arquivos `js`

Os arquivos fontes ficam na pasta `./resources/scripts`

Rode o comando `npm run watch` para escutar as alterações
Ou `npm run build` para compilar css/js files

**Comment by Diegoslourenco** [comment]
Obrigado, @laisfrigerio. Vou começar e caso eu precise de algo te aviso
